# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'interface_template2.ui'
#
# Created: Mon May  9 17:49:23 2016
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_StrategicLayer(object):
    def setupUi(self, StrategicLayer):
        StrategicLayer.setObjectName(_fromUtf8("StrategicLayer"))
        StrategicLayer.resize(1528, 817)
        self.centralwidget = QtGui.QWidget(StrategicLayer)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.main_splitter = QtGui.QSplitter(self.centralwidget)
        self.main_splitter.setOrientation(QtCore.Qt.Horizontal)
        self.main_splitter.setObjectName(_fromUtf8("main_splitter"))
        self.verticalLayoutWidget_2 = QtGui.QWidget(self.main_splitter)
        self.verticalLayoutWidget_2.setObjectName(_fromUtf8("verticalLayoutWidget_2"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_4.setMargin(0)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.main_frame = QtGui.QWidget(self.verticalLayoutWidget_2)
        self.main_frame.setObjectName(_fromUtf8("main_frame"))
        self.verticalLayout_4.addWidget(self.main_frame)
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.showCapacities = QtGui.QCheckBox(self.verticalLayoutWidget_2)
        self.showCapacities.setObjectName(_fromUtf8("showCapacities"))
        self.gridLayout.addWidget(self.showCapacities, 0, 0, 1, 1)
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        spacerItem = QtGui.QSpacerItem(6, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.label_10 = QtGui.QLabel(self.verticalLayoutWidget_2)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.horizontalLayout_3.addWidget(self.label_10)
        self.label_9 = QtGui.QLabel(self.verticalLayoutWidget_2)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.horizontalLayout_3.addWidget(self.label_9)
        self.label_8 = QtGui.QLabel(self.verticalLayoutWidget_2)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.horizontalLayout_3.addWidget(self.label_8)
        self.label_7 = QtGui.QLabel(self.verticalLayoutWidget_2)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.horizontalLayout_3.addWidget(self.label_7)
        self.label_6 = QtGui.QLabel(self.verticalLayoutWidget_2)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.horizontalLayout_3.addWidget(self.label_6)
        self.label_5 = QtGui.QLabel(self.verticalLayoutWidget_2)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.horizontalLayout_3.addWidget(self.label_5)
        self.label_4 = QtGui.QLabel(self.verticalLayoutWidget_2)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout_3.addWidget(self.label_4)
        self.label_3 = QtGui.QLabel(self.verticalLayoutWidget_2)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout_3.addWidget(self.label_3)
        self.label_2 = QtGui.QLabel(self.verticalLayoutWidget_2)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_3.addWidget(self.label_2)
        self.label = QtGui.QLabel(self.verticalLayoutWidget_2)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout_3.addWidget(self.label)
        self.label_25 = QtGui.QLabel(self.verticalLayoutWidget_2)
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.horizontalLayout_3.addWidget(self.label_25)
        self.label_24 = QtGui.QLabel(self.verticalLayoutWidget_2)
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.horizontalLayout_3.addWidget(self.label_24)
        self.label_23 = QtGui.QLabel(self.verticalLayoutWidget_2)
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.horizontalLayout_3.addWidget(self.label_23)
        self.label_22 = QtGui.QLabel(self.verticalLayoutWidget_2)
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.horizontalLayout_3.addWidget(self.label_22)
        self.label_21 = QtGui.QLabel(self.verticalLayoutWidget_2)
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.horizontalLayout_3.addWidget(self.label_21)
        self.label_20 = QtGui.QLabel(self.verticalLayoutWidget_2)
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.horizontalLayout_3.addWidget(self.label_20)
        self.label_19 = QtGui.QLabel(self.verticalLayoutWidget_2)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.horizontalLayout_3.addWidget(self.label_19)
        self.label_18 = QtGui.QLabel(self.verticalLayoutWidget_2)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.horizontalLayout_3.addWidget(self.label_18)
        self.label_17 = QtGui.QLabel(self.verticalLayoutWidget_2)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.horizontalLayout_3.addWidget(self.label_17)
        self.label_16 = QtGui.QLabel(self.verticalLayoutWidget_2)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.horizontalLayout_3.addWidget(self.label_16)
        self.label_15 = QtGui.QLabel(self.verticalLayoutWidget_2)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.horizontalLayout_3.addWidget(self.label_15)
        self.label_14 = QtGui.QLabel(self.verticalLayoutWidget_2)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.horizontalLayout_3.addWidget(self.label_14)
        self.label_13 = QtGui.QLabel(self.verticalLayoutWidget_2)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.horizontalLayout_3.addWidget(self.label_13)
        self.label_12 = QtGui.QLabel(self.verticalLayoutWidget_2)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.horizontalLayout_3.addWidget(self.label_12)
        self.gridLayout_2.addLayout(self.horizontalLayout_3, 0, 0, 1, 1)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.capacitySlider = QtGui.QSlider(self.verticalLayoutWidget_2)
        self.capacitySlider.setMaximum(23)
        self.capacitySlider.setTracking(True)
        self.capacitySlider.setOrientation(QtCore.Qt.Horizontal)
        self.capacitySlider.setTickPosition(QtGui.QSlider.TicksAbove)
        self.capacitySlider.setTickInterval(1)
        self.capacitySlider.setObjectName(_fromUtf8("capacitySlider"))
        self.horizontalLayout_4.addWidget(self.capacitySlider)
        spacerItem1 = QtGui.QSpacerItem(15, 2, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.gridLayout_2.addLayout(self.horizontalLayout_4, 1, 0, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_2, 0, 1, 1, 1)
        self.verticalLayout_4.addLayout(self.gridLayout)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.pause = QtGui.QPushButton(self.verticalLayoutWidget_2)
        self.pause.setObjectName(_fromUtf8("pause"))
        self.horizontalLayout_2.addWidget(self.pause)
        self.play = QtGui.QPushButton(self.verticalLayoutWidget_2)
        self.play.setObjectName(_fromUtf8("play"))
        self.horizontalLayout_2.addWidget(self.play)
        self.play_one_step = QtGui.QPushButton(self.verticalLayoutWidget_2)
        self.play_one_step.setObjectName(_fromUtf8("play_one_step"))
        self.horizontalLayout_2.addWidget(self.play_one_step)
        self.verticalLayout_4.addLayout(self.horizontalLayout_2)
        self.text_splitter = QtGui.QSplitter(self.main_splitter)
        self.text_splitter.setOrientation(QtCore.Qt.Vertical)
        self.text_splitter.setObjectName(_fromUtf8("text_splitter"))
        self.story = QtGui.QTextBrowser(self.text_splitter)
        self.story.setObjectName(_fromUtf8("story"))
        self.information = QtGui.QTextBrowser(self.text_splitter)
        self.information.setObjectName(_fromUtf8("information"))
        self.horizontalLayout.addWidget(self.main_splitter)
        StrategicLayer.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(StrategicLayer)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1528, 27))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        StrategicLayer.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(StrategicLayer)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        StrategicLayer.setStatusBar(self.statusbar)

        self.retranslateUi(StrategicLayer)
        QtCore.QMetaObject.connectSlotsByName(StrategicLayer)

    def retranslateUi(self, StrategicLayer):
        StrategicLayer.setWindowTitle(_translate("StrategicLayer", "MainWindow", None))
        self.showCapacities.setText(_translate("StrategicLayer", "Show Capacities", None))
        self.label_10.setText(_translate("StrategicLayer", "0", None))
        self.label_9.setText(_translate("StrategicLayer", "1", None))
        self.label_8.setText(_translate("StrategicLayer", "2", None))
        self.label_7.setText(_translate("StrategicLayer", "3", None))
        self.label_6.setText(_translate("StrategicLayer", "4", None))
        self.label_5.setText(_translate("StrategicLayer", "5", None))
        self.label_4.setText(_translate("StrategicLayer", "6", None))
        self.label_3.setText(_translate("StrategicLayer", "7", None))
        self.label_2.setText(_translate("StrategicLayer", "8", None))
        self.label.setText(_translate("StrategicLayer", "9", None))
        self.label_25.setText(_translate("StrategicLayer", "10", None))
        self.label_24.setText(_translate("StrategicLayer", "11", None))
        self.label_23.setText(_translate("StrategicLayer", "12", None))
        self.label_22.setText(_translate("StrategicLayer", "13", None))
        self.label_21.setText(_translate("StrategicLayer", "14", None))
        self.label_20.setText(_translate("StrategicLayer", "15", None))
        self.label_19.setText(_translate("StrategicLayer", "16", None))
        self.label_18.setText(_translate("StrategicLayer", "17", None))
        self.label_17.setText(_translate("StrategicLayer", "18", None))
        self.label_16.setText(_translate("StrategicLayer", "19", None))
        self.label_15.setText(_translate("StrategicLayer", "20", None))
        self.label_14.setText(_translate("StrategicLayer", "21", None))
        self.label_13.setText(_translate("StrategicLayer", "22", None))
        self.label_12.setText(_translate("StrategicLayer", "23", None))
        self.pause.setText(_translate("StrategicLayer", "Pause", None))
        self.play.setText(_translate("StrategicLayer", "Play", None))
        self.play_one_step.setText(_translate("StrategicLayer", "Play One step", None))

